PracticaWeb/PracticaWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^flylo/', include('flylo.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^flylo/', include('flylo.urls',namespace='flylo')),
]

PracticaWeb/flylo/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^flights$', views.flights2, name='flights'),
    url(r'^flights/(?P<departure>.*)/$', views.flights2, name='flights'),
    #url(r'^flights/(?P<d>\w+)(?P<departure>)$', views.flights2, name='flights'),
    url(r'^shoppingcart/$', views.shoppingcart, name='shoppingcart'),
    url(r'^buy/$', views.buy, name='buy'),
]

PracticaWeb/flylo/models.py
from __future__ import unicode_literals

from django.db import models

class Flight(models.Model):
    flight_number = models.CharField(max_length=8)
    estimated_time_departure =  models.DateTimeField()
    estimated_time_arrival =  models.DateTimeField()
    location_departure =  models.CharField(max_length=3)
    location_arrival = models.CharField(max_length=3)
    airline = models.CharField(max_length=3)
    aircraft = models.CharField(max_length=4)
    status = models.CharField(max_length=40)
    def __str__(self):
        return "["+self.flight_number+"] "+ self.location_departure +"-"+ self.location_arrival + " : "+ str(self.estimated_time_departure) + " / " + str(self.estimated_time_arrival) + " ["+ self.status +"]"


class Airline(models.Model):
    name = models.CharField(max_length=40)
    category = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Airplane(models.Model):
    model = models.CharField(max_length=40)
    reference_code = models.CharField(max_length=100)
    number_seats_tourist = models.CharField(max_length=5)
    number_seats_business = models.CharField(max_length=5)
    number_seats_excellence = models.CharField(max_length=5)
    category = models.ForeignKey(Airline, on_delete=models.CASCADE)
    def __str__(self):
        return "["+self.model+"] "+self.reference_code

PracticaWeb/flylo/views.py
from django.shortcuts import render
from .models import Flight
from django import forms
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from itertools import chain

def index(request):
    flights_by_departure = Flight.objects.all()
    context = {
        'flights':flights_by_departure,
    }
    return render(request, 'flylo/index.html', context)
  

""" 
def flights(request,departure):
    flights_by_departure = Flight.objects.filter(location_departure=departure)
    context = {
        'flights':flights_by_departure,
        'departure':departure,
    }
    return render(request, 'flylo/flights.html', context)
"""

def flights2(request):
    if request.POST:
      selectedDeparture = request.POST["d"]
      flights_by_departure = Flight.objects.filter(location_departure=selectedDeparture)
      context = {
          'flights':flights_by_departure,
          
      }
      request.session["selectedDeparture"] = selectedDeparture


    return render(request, 'flylo/flights3.html', context)

def shoppingcart(request):
  selectedFlights =[]
  selected_to_return=[] #Llista de vols que volem tornada
  totalFlights=[]
  returnFlights=[]
  for key in request.POST:
     if key.startswith("checkbox") :
        selectedFlights.append(request.POST[key])
        
     if key.startswith("ret") :
        selected_to_return.append(request.POST[key])
  request.session["selectedFligths"] = selectedFlights
  

  totalFlights = Flight.objects.filter(pk__in=selectedFlights)
  for departure in Flight.objects.values_list("location_arrival", flat=True).filter(pk__in=selected_to_return):
    for flight in Flight.objects.filter(location_departure=departure).filter(location_arrival=request.session["selectedDeparture"]):
      returnFlights.append(flight)
  result_list = list(chain(totalFlights,returnFlights))
  print returnFlights
  context = {
        'flights':result_list,
        'returnflights':returnFlights,
  }
  if not selected_to_return: #Si no hi ha res a la llista de return va a buy 
    return HttpResponseRedirect(reverse('flylo:buy'),context)
  else:
    return render(request, 'flylo/flights3.html', context) # si hi va a tornada per selecciona vols
    
    
    
    
  

def buy(request):
    flights_selected = Flight.objects.filter(pk__in=request.session["selectedFligths"])
    context = {
        'flights':flights_selected,
    }
    return render(request, 'flylo/buy.html', context)

PracticaWeb/flylo/templates/flylo/buy.html
{% if flights %}
	<H2>Buy</H2>
    <ul>
    {% for flight in flights %}
    	<li><a href="{% url 'flights' departure %}{{flight.flight_number}}">{{ flight.flight_number}} </a> from {{flight.location_departure}} to {{flight.location_arrival}} STATUS:{{flight.status}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Flights are available.</p>
{% endif %} 

PracticaWeb/flylo/templates/flylo/flights.html
{% if flights %}
	<H2>You're looking at our flights from {{ departure }}:</H2>
    <ul>
    {% for flight in flights %}
    	<li><a href="{% url 'flights' departure %}{{flight.flight_number}}">{{ flight.flight_number}} </a> from {{flight.location_departure}} to {{flight.location_arrival}} STATUS:{{flight.status}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Flights are available.</p>
{% endif %} 

PracticaWeb/flylo/templates/flylo/flights3.html
 {% if flights %}
<H2>
   You're looking at our flights from {{ departure }}:
   </H2>
   <form action="{% url 'flylo:shoppingcart'%}" method="post">
   {% csrf_token %}
    {% for flight in flights %}    	
     <label>
       <input type= checkbox name="checkbox{{ flight.id }}" id="checkbox{{ flight.id }}" value="{{ flight.id }}"/> 
       <a href="{% url 'flights' departure %}{{flight.flight_number}}">{{ flight.flight_number}} </a> to {{flight.location_arrival}} 
       Seats: <input type=text name="seats{{ flight.id }}" id="seats{{ flight.id }}" value=""/>
       {% if returnflights %}
       {% else %}
          Return: <input type= checkbox name="ret{{ flight.id }}" id="ret{{ flight.id }}" value="{{ flight.id }}"/> 
       {% endif %} 
     </label>
         <BR>
    {% endfor %}
   <input type="submit" value="Go to Shopping cart" />
	</form>
{% else %}
    <p>No Flights are available.</p>
{% endif %}

PracticaWeb/flylo/templates/flylo/index.html
{% if flights %}
<H2>
   You're looking at all of our flights:
   </H2>
   <form action="{% url 'flights' %}" method="post">{% csrf_token %}
	   	<SELECT NAME="d">
		    {% for flight in flights %}
		    	<option value="{{flight.location_departure}}">{{ flight.location_departure }} </option>
		    {% endfor %}
		</SELECT>
	  	<input type="submit" value="Go to Flights page" />
	</form>
{% else %}
    <p>No Flights are available.</p>
{% endif %}